services:
  app:
    build:
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - firebase
    develop:
      watch:
        - action: rebuild
          path: ../app/package.json
        - action: sync
          path: ../app
          target: ./app
          ignore:
            - ../app/node_modules

  functions:
    build:
      target: dev
    volumes:
      - functions-lib:/firebase/functions/lib #Firebase コンテナの/libと共有する
    develop:
      watch:
        - action: rebuild
          path: ../firebase/functions/src
        - action: sync
          path: ../firebase/functions
          target: ./firebase/functions
          ignore:
            - ../firebase/functions/node_modules
            - ../firebase/functions/lib

  firebase:
    build:
      context: ..
      dockerfile: docker/firebase.Dockerfile
    ports:
      - "4000:4000" # Firebase Emulator UI
      - "4500:4500" # Firebase Pub/Sub
      - "8080:8080" # Firestore Emulator
      - "8085:8085" # Datastore Emulator
      - "9099:9099" # Authentication Emulator
      - "9199:9199" # Cloud Storage Emulator
      - "5001:5001" # Cloud functions Emulator
    volumes:
      - functions-lib:/firebase/functions/lib #Functions コンテナの/libと共有する
    environment:
      - "FIREBASE_FIRESTORE_EMULATOR_HOST=0.0.0.0:8080"
      - "FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:9099"
      - "FIREBASE_CLOUD_STORAGE_EMULATOR_HOST=0.0.0.0:9199"
      - "FIREBASE_CLOUD_FUNCTIONS_EMULATOR_HOST=0.0.0:5001"
      
volumes:
  functions-lib: