services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    ports:
      - "3000:3000"

  functions:
    build:
      context: ..
      dockerfile: docker/functions.Dockerfile
      target: prod